import os
import sys
import math
from snakemake.utils import min_version

min_version("7.20")

CONDA = "../envs/env.yml"
CONDA = "fiberseq-smk"
PAT_DATA = config.pop("paternal")
MAT_DATA = config.pop("maternal")
HIFI_BAM = config.pop("hifi_bam")
VCF = config.pop("vcf")
SAMPLE = config.pop("sample")
REFERENCE = config.pop("reference")


wildcard_constraints:
    sm="|".join([SAMPLE]),
    hap="pat|mat",


include: "rules/common.smk"
include: "rules/canu.smk"
include: "rules/hiphase.smk"
include: "rules/merge.smk"


rule all:
    input:
        expand(rules.hiphase_read_list.output, sm=SAMPLE),
        expand(rules.canu_read_list.output, sm=SAMPLE),
        expand(rules.merge_kmer_and_variant_phasing.output, sm=SAMPLE),
        expand(rules.haplotaged_bam.output, sm=SAMPLE),
