[project]
authors = ["Mitchell R. Vollger <mrvollger@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "k-mer-variant-phasing"
platforms = ["osx-64", "linux-64"]
version = "0.0.2"

[tasks]
fmt = "ruff format . && taplo format pixi.toml && snakefmt workflow/"
test = { cmd = [
  "snakemake",
  # once established you can add more arguments with your test data here
] }
snakemake = { cmd = "cd $INIT_CWD && snakemake -s $PIXI_PROJECT_ROOT/workflow/Snakefile" }


[dependencies]
conda = "*"
snakemake = "==8.21"
snakefmt = "*"
ruff = "*"
taplo = "*"
snakemake-executor-plugin-slurm = "*"
