[project]
authors = ["Mitchell R. Vollger <mrvollger@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "k-mer-variant-phasing"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]
fmt = "ruff format . && taplo format pixi.toml && snakefmt workflow/"
test-data = { cmd = [
  "cd",
  "$INIT_CWD",
  "&&",
  "mkdir",
  "-p",
  "k-mer-test-data",
  "&&",
  "aws",
  "s3",
  "--no-sign-request",
  "sync",
  "s3://stergachis-public1/Mitchell/k-mer-test-data",
  "k-mer-test-data/",
] }
test = { cmd = [
  "cd",
  "$INIT_CWD/k-mer-test-data",
  "&&",
  "snakemake",
  "-s",
  "$PIXI_PROJECT_ROOT/workflow/Snakefile",
  "--config",
  "sample=test",
  "reference=test.fa",
  "hifi_bam=test.bam",
  "skip_checks=true",
  "align=true",
  "n_chunks=2",
  "-k",
], depends_on = [
  "test-data",
] }
snakemake = { cmd = "cd $INIT_CWD && snakemake -s $PIXI_PROJECT_ROOT/workflow/Snakefile" }


[dependencies]
conda = "*"
snakemake = "==8.21"
snakefmt = "*"
ruff = "*"
taplo = "*"
snakemake-executor-plugin-slurm = "*"
awscli = "2.22"
