sample: "GM12878" # sample name that with prefix your results
hifi_bam: test_data/GM12878.hifi.chr20.bam # must be indexed (.bai)
clean_bam: true # replace all read groups in the bam with the sample name
vcf: test_data/chr20.vcf.gz # must be indexed (.tbi)
clean_vcf: true # replace the first sample name in the VCF with the pipeline sample name
paternal: test_data/NA12891.chr20.bam # paternal sequencing data, can be sam, bam, cram, fa, or fq
maternal: test_data/NA12892.chr20.bam # maternal sequencing data, can be sam, bam, cram, fa, or fq
reference: test_data/chr20.fa # reference that the hifi bam and vcf correspond to