# sample name that with prefix your results
sample: "test_GM12878"

# reference that the hifi bam and vcf correspond to, must be indexed (.fai)
reference: test_data/chr20.fa

# Hifi bam to phase, must be indexed (.bai)
hifi_bam: test_data/GM12878.hifi.chr20.bam
