default-resources:
  - disk_mb=4096
  - mem_mb=8096
  - time=600
  - gpus=0
rerun-incomplete: True
rerun-triggers: mtime 
restart-times: 0
printshellcmds: True
reason: True
use-conda: True
use-singularity: True
show-failed-logs: True 
