name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # pixi test
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ewaterman/setup-apptainer@v2 # Or the latest version available
        with:
          apptainer-version: 'latest' # Specify a version or 'latest'
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.50.0
          cache: true
      - run: pixi run test
